Update push.yml

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -134,9 +134,9 @@ jobs:
           echo "src-git routing https://git.openwrt.org/feed/routing.git;openwrt-23.05" >> feeds.conf
           echo "src-git passwall_packages https://github.com/peditx/openwrt-passwall-packages.git;main" >> feeds.conf
           ./scripts/feeds update -a
-           ./scripts/feeds install -a || { echo "Feed update/install failed"; exit 1; }
+          ./scripts/feeds install -a || { echo "Feed update/install failed"; exit 1; }
           ./scripts/feeds install -a -f -p passwall_packages || { echo "Passwall packages install failed"; exit 1; }
-          echo "CONFIG_ALL_NONSHARED=n" > .config
+           echo "CONFIG_ALL_NONSHARED=n" > .config
           echo "CONFIG_ALL_KMODS=n" >> .config
           echo "CONFIG_ALL=n" >> .config
           echo "CONFIG_AUTOREMOVE=n" >> .config
@@ -147,7 +147,6 @@ jobs:
         run: |
           cd sdk
           make download -j8
-          find dl -size -1024c -exec ls -l {} \;
 
       - name: Compile Packages
         id: compile
@@ -164,6 +163,7 @@ jobs:
             IFS=',' read -ra DIRS <<< "$CHANGED_DIRS"
             for DIR in "${DIRS[@]}"; do
               if [ -d "package/feeds/passwall_packages/$DIR" ]; then
+                cd sdk
                 make package/feeds/passwall_packages/$DIR/compile -j$(nproc) V=s || exit 1
               else
                 echo "Directory $DIR does not exist"
