Update push.yml

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -134,9 +134,8 @@ jobs:
           echo "src-git routing https://git.openwrt.org/feed/routing.git;openwrt-23.05" >> feeds.conf
           echo "src-git passwall_packages https://github.com/peditx/openwrt-passwall-packages.git;main" >> feeds.conf
           ./scripts/feeds update -a
-          ./scripts/feeds install -a || { echo "Feed update/install failed"; exit 1; }
-          ./scripts/feeds install -a -f -p passwall_packages || { echo "Passwall packages install failed
-                    ./scripts/feeds install -a -f -p passwall_packages || { echo "Passwall packages install failed"; exit 1; }
+           ./scripts/feeds install -a || { echo "Feed update/install failed"; exit 1; }
+          ./scripts/feeds install -a -f -p passwall_packages || { echo "Passwall packages install failed"; exit 1; }
           echo "CONFIG_ALL_NONSHARED=n" > .config
           echo "CONFIG_ALL_KMODS=n" >> .config
           echo "CONFIG_ALL=n" >> .config
@@ -157,7 +156,7 @@ jobs:
           force_build="${{ github.event.inputs.force_build }}"
           if [ "$force_build" == "true" ]; then
             echo "Force build is enabled."
-            make -j$(nproc) V=s $(for package in chinadns-ng dns2socks dns2tcp gn hysteria ipt2socks microsocks naiveproxy pdnsd-alt shadowsocksr-libev shadowsocks-rust simple-obfs sing-box ssocks tcping trojan trojan-go trojan-plus tuic-client v2ray-core v2ray-geodata v2ray-plugin xray-core xray-plugin; do echo "package/feeds/passwall_packages/$package/compile"; done)
+            make -j$(nproc) V=s $(for package in brook chinadns-ng dns2socks dns2tcp gn hysteria ipt2socks microsocks naiveproxy pdnsd-alt shadowsocksr-libev shadowsocks-rust simple-obfs sing-box ssocks tcping trojan trojan-go trojan-plus tuic-client v2ray-core v2ray-geodata v2ray-plugin xray-core xray-plugin; do echo "package/feeds/passwall_packages/$package/compile"; done)
           elif [ -z "$CHANGED_DIRS" ]; then
             echo "No changes detected"
             exit 0
