Update push.yml

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -16,10 +16,10 @@ on:
       force_build:
         description: 'Force build and upload'
         required: true
-        default: 'false'
+        default: 'true'
 
 env:
-  TZ: Asia/Shanghai
+  TZ: Asia/Tehran
   packages: ${{ github.repository }}
 
 jobs:
@@ -135,7 +135,7 @@ jobs:
           echo "src-git passwall_packages https://github.com/peditx/openwrt-passwall-packages.git;main" >> feeds.conf
           ./scripts/feeds update -a
           ./scripts/feeds install -a || { echo "Feed update/install failed"; exit 1; }
-          ./scripts/feeds install -a -f -p passwall_packages || { echo "Passwall packages install failed"; exit 1; }
+           ./scripts/feeds install -a -f -p passwall_packages || { echo "Passwall packages install failed"; exit 1; }
           echo "CONFIG_ALL_NONSHARED=n" > .config
           echo "CONFIG_ALL_KMODS=n" >> .config
           echo "CONFIG_ALL=n" >> .config
@@ -173,7 +173,7 @@ jobs:
       - name: Build Packages for ${{ matrix.platform }}
         run: |
           cd sdk
-          make package/feeds/passwall_packages/compile V=s || { echo "Build failed"; exit 1; }
+          make package/feeds/passwall_packages/compile -j$(nproc) V=s || { echo "Build failed"; exit 1; }
 
       - name: Debug Information
         run: |
